server:
  port: 8080
  servlet:
    context-path: /

spring:
  redis:
    host: 101.43.161.206
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
