/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jvm_1_memory_NativeMethod */

#ifndef _Included_com_example_jvm_1_memory_NativeMethod
#define _Included_com_example_jvm_1_memory_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jvm_1_memory_NativeMethod
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_jvm_11_1memory_NativeMethod_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
